#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	mkd="mkdir -pv"

# Colorize commands when possible.
alias \
	ls="ls -hNCF --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	trem="transmission-remote" \
	YT="youtube-viewer" \
	sdn="sudo shutdown -h now" \
	e="$EDITOR" \
	v="$EDITOR" \
	ll='ls -alF' \
	la='ls -AF' \
	l='ls' \
	cfg='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME' \
	sus='systemctl suspend' \
	se='sudoedit' \
	slogout='gnome-session-quit --force' \
	xo='xdg-open' \
	py='python'

alias \
	svn='svn --config-dir $XDG_CONFIG_HOME/subversion'
